version: "2"
run:
  concurrency: 4
linters:
  default: none
  enable:
    - dogsled
    - errcheck
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    gocognit:
      min-complexity: 40
    goconst:
      min-len: 5
      min-occurrences: 5
    gocritic:
      disabled-checks:
        - wrapperFunc
        - dupImport
        - ifElseChain
        - octalLiteral
        - hugeParam
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 140
    misspell:
      locale: UK
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: _test.go
        text: dot-imports
        source: github.com/smartystreets/goconvey/convey
      - linters:
          - gosec
        path: _mocker.go
        text: integer overflow
      - linters:
          - revive
        path: aws_utils.go
        text: unreachable-code
        source: log.Fatal
      - linters:
          - revive
        path: initialise.go
        text: unreachable-code
        source: log.Fatal
issues:
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
