FROM golang:1.24.2-bullseye AS base

RUN git config --global --add safe.directory /go

ENV GOCACHE=/go/.go/cache GOPATH=/go/.go/path TZ=Europe/London

RUN GOBIN=/bin go install github.com/cespare/reflex@v0.3.1
RUN PATH=$PATH:/bin

# Clean cache, as we want all modules in the container to be under /go/.go/path
RUN go clean -modcache

# Map between the working directories of dev and live
RUN ln -s /go /dp-identity-api
WORKDIR /dp-identity-api
