swagger: "2.0"
info:
  title: dp-identity-api
  description: "An API used to manage the authorisation of users accessing data publishing services."
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
schemes:
  - http
tags:
  - name: "hello"
paths:
  /hello:
    get:
      tags:
        - hello
      summary: Example hello world endpoint
      description: Returns an example payload.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/HelloResponse"
        500:
          $ref: '#/responses/InternalError'
  /tokens:
    post:
      tags:
        - token
      summary: "Creates tokens for authorisation, ID and refresh for authenticated users"
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: "The email and password for a user"
          schema:
            type: object
            required:
              - user
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        201:
          description: "Created"
          headers: 
            Authorization:
              type: string
              description: "Auth token"
            ID:
              type: string
              description: "ID token"
            Refresh:
              type: string
              description: "Refresh token"
        400:
          description: "Invalid request. Empty or invalid email or empty password."
          schema:
            $ref: '#/definitions/LoginErrorList'
        401:
          description: "Email or password are not authenticated"
          schema:
            $ref: '#/definitions/LoginErrorList'
        403:
          description: "Forbidden. Too many login attempts"
          schema:
            $ref: '#/definitions/LoginErrorList'

        500:
          description: "Unexpected internal error"
          schema:
            $ref: '#/definitions/LoginErrorList'

responses:
  InternalError:
    description: "Failed to process the request due to an internal error"

definitions:
  HelloResponse:
    type: object
    properties:
      message:
        type: string
        description: "Message returned by hello world endpoint"
        example: "Hello, world!"

  LoginErrorList:
    description: "A list of errors"
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/LoginErrorResponse'

  LoginErrorResponse:
    description: "an individual error"
    type: object
    properties:
      error: 
        type: string
        description: "returned error description"
      message: 
        type: string
        description: "returned message"
      source: 
        $ref:  '#/definitions/LoginErrorSource'

  LoginErrorSource:
    description : "returned field and parameter"
    type: object
    properties: 
      field:
        type: string
        description: "returned field name on which error has occurred"
      param:
        type: string
        description: "returned parameter on which an error has occurred"
