swagger: "2.0"
info:
  title: dp-identity-api
  description: "An API used to manage the authorisation of users accessing data publishing services."
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
schemes:
  - http
tags:
  - name: "hello"
paths:
  /hello:
    get:
      tags:
        - hello
      summary: Example hello world endpoint
      description: Returns an example payload.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/HelloResponse"
        500:
          $ref: '#/responses/InternalError'
  /tokens:
    post:
      tags:
        - token
      summary: "Creates tokens for authorisation, ID and refresh for authenticated users"
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: "The email and password for a user"
          schema:
            type: object
            required:
              - user
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        201:
          description: "Created"
          headers:
            Authorization:
              type: string
              description: "Auth token"
            ID:
              type: string
              description: "ID token"
            Refresh:
              type: string
              description: "Refresh token"
          schema:
            $ref: '#/definitions/ExpirationTime'

        400:
          description: "Invalid request. Empty or invalid email or empty password."
          schema:
            $ref: '#/definitions/TokensErrorList'
        401:
          description: "Email or password are not authenticated"
          schema:
            $ref: '#/definitions/TokensErrorList'
        403:
          description: "Forbidden. Too many login attempts"
          schema:
            $ref: '#/definitions/TokensErrorList'

        500:
          description: "Unexpected internal error"
          schema:
            $ref: '#/definitions/LoginErrorList'
  /users:
    post:
      tags:
        - users
        - Private
      summary: "Creates a new user"
      description: "Creates a new user in cognito"
      consumes:
        - application/json
      produces:
         - "application/json"
      parameters:
        - in: body
          name: user
          description: "The email and username for a user."
          schema:
            required: ["email","username"]
            type: object
            properties:
              email:
                type: string
                example: "email@ons.gov.uk"
              username:
                type: string
                example: "smileons"
      responses:
        201:
          description: "The user is created"
          schema:
            $ref: '#/definitions/NewUser'
        400:
          description: "Unable to validate the email/username in the request"
          schema:
            $ref: '#/definitions/LoginErrorList'
        500:
          description: "Invalid request body."
          schema:
            $ref: '#/definitions/LoginErrorList'
  /delete:
      tags:
        - token
      summary: "Signs out a user, invalidating their access tokens"
      consumes:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: "The users access token as bearer token"
      responses:
        204:
          description: "No Content - Successful sign out"
        400:
          description: "Invalid request. Missing, malformed or invalid access token provided"
          schema:
            $ref: '#/definitions/TokensErrorResponse'
        500:
          description: "Unexpected internal error"
          schema:
            $ref: '#/definitions/TokensErrorResponse'

responses:
  InternalError:
    description: "Failed to process the request due to an internal error"

definitions:
  HelloResponse:
    type: object
    properties:
      message:
        type: string
        description: "Message returned by hello world endpoint"
        example: "Hello, world!"

  ExpirationTime:
    type: object
    properties:
      message:
        type: string
        description: "Expiration Time, UTC ISO 8601"
        example: "YYYY-MM-DD hh-mm-ssZ"

  TokensErrorList:
    description: "A list of errors"
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/TokensErrorResponse'

  TokensErrorResponse:
    description: "an individual error"
    type: object
    properties:
      error:
        type: string
        description: "returned error description"
      message:
        type: string
        description: "returned message"
      source:
        $ref:  '#/definitions/TokensErrorSource'

  TokensErrorSource:
    description : "returned field and parameter"
    type: object
    properties:
      field:
        type: string
        description: "returned field name on which error has occurred"
      param:
        type: string
        description: "returned parameter on which an error has occurred"

  NewUser:
    description: "A model for the response body creating the user"
    type: object
    properties:
      Attributes:
        description: "Information about list of user type attribute"
        type: array
        items:
           $ref: '#/definitions/AttributeType'
      Enabled:
        description: "Specifies whether the user is enabled"
        type: boolean
      MFAOptions:
        description: "The MFA options for the user."
        type: array
        items: 
           $ref: '#/definitions/MFAOptionType'
      UserCreateDate:
        description: "The creation date of the user"
        type: string
        format: date-time
      UserLastModifiedDate:
        description: "The last modified date of the user."
        type: string
        format: date-time
      UserStatus: 
        description: "The current status of the user"
        type: string
        enum: [UNCONFIRMED, CONFIRMED, ARCHIVED, COMPROMISED, UNKNOWN, RESET_REQUIRED, FORCE_CHANGE_PASSWORD]
        example: "CONFIRMED"
      Username:
        description: "The username of the user"    
        type: string
        example: "smileons"

  AttributeType:
    description: "Specifies the attribute type standard or custom."
    type: object
    properties:
      Name:
        description: "The name of the attribute."
        type: string
      Value:
        description: "value of the attribute"
        type: string
  
  MFAOptionType:
    description: "SMS MFA configuration type"
    type: object
    properties:
      AttributeName:
        description: "The attribute name of the MFA option type. The only valid value is phone_number."
        type: string
      DeliveryMedium:
        description: "Parameter for SMS delivery medium value."
        type: string