// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-authorisation/v2/authorisation"
	cognitoClient "github.com/ONSdigital/dp-identity-api/cognito"
	"github.com/ONSdigital/dp-identity-api/config"
	"github.com/ONSdigital/dp-identity-api/service"
	"net/http"
	"sync"
)

// Ensure, that InitialiserMock does implement service.Initialiser.
// If this is not the case, regenerate this file with moq.
var _ service.Initialiser = &InitialiserMock{}

// InitialiserMock is a mock implementation of service.Initialiser.
//
// 	func TestSomethingThatUsesInitialiser(t *testing.T) {
//
// 		// make and configure a mocked service.Initialiser
// 		mockedInitialiser := &InitialiserMock{
// 			DoGetAuthorisationMiddlewareFunc: func(ctx context.Context, authorisationConfig *authorisation.Config) (authorisation.Middleware, error) {
// 				panic("mock out the DoGetAuthorisationMiddleware method")
// 			},
// 			DoGetCognitoClientFunc: func(region string) cognitoClient.Client {
// 				panic("mock out the DoGetCognitoClient method")
// 			},
// 			DoGetHTTPServerFunc: func(bindAddr string, router http.Handler) service.HTTPServer {
// 				panic("mock out the DoGetHTTPServer method")
// 			},
// 			DoGetHealthCheckFunc: func(cfg *config.Config, buildTime string, gitCommit string, version string) (service.HealthChecker, error) {
// 				panic("mock out the DoGetHealthCheck method")
// 			},
// 		}
//
// 		// use mockedInitialiser in code that requires service.Initialiser
// 		// and then make assertions.
//
// 	}
type InitialiserMock struct {
	// DoGetAuthorisationMiddlewareFunc mocks the DoGetAuthorisationMiddleware method.
	DoGetAuthorisationMiddlewareFunc func(ctx context.Context, authorisationConfig *authorisation.Config) (authorisation.Middleware, error)

	// DoGetCognitoClientFunc mocks the DoGetCognitoClient method.
	DoGetCognitoClientFunc func(region string) cognitoClient.Client

	// DoGetHTTPServerFunc mocks the DoGetHTTPServer method.
	DoGetHTTPServerFunc func(bindAddr string, router http.Handler) service.HTTPServer

	// DoGetHealthCheckFunc mocks the DoGetHealthCheck method.
	DoGetHealthCheckFunc func(cfg *config.Config, buildTime string, gitCommit string, version string) (service.HealthChecker, error)

	// calls tracks calls to the methods.
	calls struct {
		// DoGetAuthorisationMiddleware holds details about calls to the DoGetAuthorisationMiddleware method.
		DoGetAuthorisationMiddleware []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthorisationConfig is the authorisationConfig argument value.
			AuthorisationConfig *authorisation.Config
		}
		// DoGetCognitoClient holds details about calls to the DoGetCognitoClient method.
		DoGetCognitoClient []struct {
			// Region is the region argument value.
			Region string
		}
		// DoGetHTTPServer holds details about calls to the DoGetHTTPServer method.
		DoGetHTTPServer []struct {
			// BindAddr is the bindAddr argument value.
			BindAddr string
			// Router is the router argument value.
			Router http.Handler
		}
		// DoGetHealthCheck holds details about calls to the DoGetHealthCheck method.
		DoGetHealthCheck []struct {
			// Cfg is the cfg argument value.
			Cfg *config.Config
			// BuildTime is the buildTime argument value.
			BuildTime string
			// GitCommit is the gitCommit argument value.
			GitCommit string
			// Version is the version argument value.
			Version string
		}
	}
	lockDoGetAuthorisationMiddleware sync.RWMutex
	lockDoGetCognitoClient           sync.RWMutex
	lockDoGetHTTPServer              sync.RWMutex
	lockDoGetHealthCheck             sync.RWMutex
}

// DoGetAuthorisationMiddleware calls DoGetAuthorisationMiddlewareFunc.
func (mock *InitialiserMock) DoGetAuthorisationMiddleware(ctx context.Context, authorisationConfig *authorisation.Config) (authorisation.Middleware, error) {
	if mock.DoGetAuthorisationMiddlewareFunc == nil {
		panic("InitialiserMock.DoGetAuthorisationMiddlewareFunc: method is nil but Initialiser.DoGetAuthorisationMiddleware was just called")
	}
	callInfo := struct {
		Ctx                 context.Context
		AuthorisationConfig *authorisation.Config
	}{
		Ctx:                 ctx,
		AuthorisationConfig: authorisationConfig,
	}
	mock.lockDoGetAuthorisationMiddleware.Lock()
	mock.calls.DoGetAuthorisationMiddleware = append(mock.calls.DoGetAuthorisationMiddleware, callInfo)
	mock.lockDoGetAuthorisationMiddleware.Unlock()
	return mock.DoGetAuthorisationMiddlewareFunc(ctx, authorisationConfig)
}

// DoGetAuthorisationMiddlewareCalls gets all the calls that were made to DoGetAuthorisationMiddleware.
// Check the length with:
//     len(mockedInitialiser.DoGetAuthorisationMiddlewareCalls())
func (mock *InitialiserMock) DoGetAuthorisationMiddlewareCalls() []struct {
	Ctx                 context.Context
	AuthorisationConfig *authorisation.Config
} {
	var calls []struct {
		Ctx                 context.Context
		AuthorisationConfig *authorisation.Config
	}
	mock.lockDoGetAuthorisationMiddleware.RLock()
	calls = mock.calls.DoGetAuthorisationMiddleware
	mock.lockDoGetAuthorisationMiddleware.RUnlock()
	return calls
}

// DoGetCognitoClient calls DoGetCognitoClientFunc.
func (mock *InitialiserMock) DoGetCognitoClient(region string) cognitoClient.Client {
	if mock.DoGetCognitoClientFunc == nil {
		panic("InitialiserMock.DoGetCognitoClientFunc: method is nil but Initialiser.DoGetCognitoClient was just called")
	}
	callInfo := struct {
		Region string
	}{
		Region: region,
	}
	mock.lockDoGetCognitoClient.Lock()
	mock.calls.DoGetCognitoClient = append(mock.calls.DoGetCognitoClient, callInfo)
	mock.lockDoGetCognitoClient.Unlock()
	return mock.DoGetCognitoClientFunc(region)
}

// DoGetCognitoClientCalls gets all the calls that were made to DoGetCognitoClient.
// Check the length with:
//     len(mockedInitialiser.DoGetCognitoClientCalls())
func (mock *InitialiserMock) DoGetCognitoClientCalls() []struct {
	Region string
} {
	var calls []struct {
		Region string
	}
	mock.lockDoGetCognitoClient.RLock()
	calls = mock.calls.DoGetCognitoClient
	mock.lockDoGetCognitoClient.RUnlock()
	return calls
}

// DoGetHTTPServer calls DoGetHTTPServerFunc.
func (mock *InitialiserMock) DoGetHTTPServer(bindAddr string, router http.Handler) service.HTTPServer {
	if mock.DoGetHTTPServerFunc == nil {
		panic("InitialiserMock.DoGetHTTPServerFunc: method is nil but Initialiser.DoGetHTTPServer was just called")
	}
	callInfo := struct {
		BindAddr string
		Router   http.Handler
	}{
		BindAddr: bindAddr,
		Router:   router,
	}
	mock.lockDoGetHTTPServer.Lock()
	mock.calls.DoGetHTTPServer = append(mock.calls.DoGetHTTPServer, callInfo)
	mock.lockDoGetHTTPServer.Unlock()
	return mock.DoGetHTTPServerFunc(bindAddr, router)
}

// DoGetHTTPServerCalls gets all the calls that were made to DoGetHTTPServer.
// Check the length with:
//     len(mockedInitialiser.DoGetHTTPServerCalls())
func (mock *InitialiserMock) DoGetHTTPServerCalls() []struct {
	BindAddr string
	Router   http.Handler
} {
	var calls []struct {
		BindAddr string
		Router   http.Handler
	}
	mock.lockDoGetHTTPServer.RLock()
	calls = mock.calls.DoGetHTTPServer
	mock.lockDoGetHTTPServer.RUnlock()
	return calls
}

// DoGetHealthCheck calls DoGetHealthCheckFunc.
func (mock *InitialiserMock) DoGetHealthCheck(cfg *config.Config, buildTime string, gitCommit string, version string) (service.HealthChecker, error) {
	if mock.DoGetHealthCheckFunc == nil {
		panic("InitialiserMock.DoGetHealthCheckFunc: method is nil but Initialiser.DoGetHealthCheck was just called")
	}
	callInfo := struct {
		Cfg       *config.Config
		BuildTime string
		GitCommit string
		Version   string
	}{
		Cfg:       cfg,
		BuildTime: buildTime,
		GitCommit: gitCommit,
		Version:   version,
	}
	mock.lockDoGetHealthCheck.Lock()
	mock.calls.DoGetHealthCheck = append(mock.calls.DoGetHealthCheck, callInfo)
	mock.lockDoGetHealthCheck.Unlock()
	return mock.DoGetHealthCheckFunc(cfg, buildTime, gitCommit, version)
}

// DoGetHealthCheckCalls gets all the calls that were made to DoGetHealthCheck.
// Check the length with:
//     len(mockedInitialiser.DoGetHealthCheckCalls())
func (mock *InitialiserMock) DoGetHealthCheckCalls() []struct {
	Cfg       *config.Config
	BuildTime string
	GitCommit string
	Version   string
} {
	var calls []struct {
		Cfg       *config.Config
		BuildTime string
		GitCommit string
		Version   string
	}
	mock.lockDoGetHealthCheck.RLock()
	calls = mock.calls.DoGetHealthCheck
	mock.lockDoGetHealthCheck.RUnlock()
	return calls
}
