---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.4-bullseye

inputs:
  - name: dp-identity-api

outputs:
  - name: build

run:
  path: dp-identity-api/ci/scripts/build.sh
